// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MessageService service

type MessageService interface {
	SendMessage(ctx context.Context, in *MessageRequest, opts ...client.CallOption) (*MessageResponse, error)
	ConsumeMessage(ctx context.Context, in *ConsumeRequest, opts ...client.CallOption) (*ConsumeResponse, error)
}

type messageService struct {
	c    client.Client
	name string
}

func NewMessageService(name string, c client.Client) MessageService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "messageservice"
	}
	return &messageService{
		c:    c,
		name: name,
	}
}

func (c *messageService) SendMessage(ctx context.Context, in *MessageRequest, opts ...client.CallOption) (*MessageResponse, error) {
	req := c.c.NewRequest(c.name, "MessageService.SendMessage", in)
	out := new(MessageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageService) ConsumeMessage(ctx context.Context, in *ConsumeRequest, opts ...client.CallOption) (*ConsumeResponse, error) {
	req := c.c.NewRequest(c.name, "MessageService.ConsumeMessage", in)
	out := new(ConsumeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MessageService service

type MessageServiceHandler interface {
	SendMessage(context.Context, *MessageRequest, *MessageResponse) error
	ConsumeMessage(context.Context, *ConsumeRequest, *ConsumeResponse) error
}

func RegisterMessageServiceHandler(s server.Server, hdlr MessageServiceHandler, opts ...server.HandlerOption) error {
	type messageService interface {
		SendMessage(ctx context.Context, in *MessageRequest, out *MessageResponse) error
		ConsumeMessage(ctx context.Context, in *ConsumeRequest, out *ConsumeResponse) error
	}
	type MessageService struct {
		messageService
	}
	h := &messageServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MessageService{h}, opts...))
}

type messageServiceHandler struct {
	MessageServiceHandler
}

func (h *messageServiceHandler) SendMessage(ctx context.Context, in *MessageRequest, out *MessageResponse) error {
	return h.MessageServiceHandler.SendMessage(ctx, in, out)
}

func (h *messageServiceHandler) ConsumeMessage(ctx context.Context, in *ConsumeRequest, out *ConsumeResponse) error {
	return h.MessageServiceHandler.ConsumeMessage(ctx, in, out)
}
