// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Valid                bool     `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	Token                *Token   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Response) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*Key)(nil), "protos.Key")
	proto.RegisterType((*Token)(nil), "protos.Token")
	proto.RegisterType((*Response)(nil), "protos.Response")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc6, 0x30,
	0x10, 0x84, 0x8d, 0x6d, 0xb5, 0x6e, 0x29, 0x94, 0x45, 0x30, 0x08, 0x42, 0x89, 0x97, 0x82, 0xd0,
	0x43, 0x7d, 0x02, 0x4f, 0x1e, 0x7a, 0x0b, 0xe2, 0x3d, 0xda, 0xa5, 0x95, 0x6a, 0x53, 0x4c, 0x2a,
	0xf4, 0xed, 0x25, 0x49, 0x73, 0xf8, 0xe1, 0x3f, 0x65, 0x86, 0xec, 0xec, 0x7c, 0x2c, 0x80, 0xda,
	0xec, 0xd4, 0xae, 0xbf, 0xda, 0x6a, 0xbc, 0xf2, 0x8f, 0x11, 0x77, 0x90, 0xf4, 0xb4, 0x63, 0x05,
	0xc9, 0x4c, 0x3b, 0x67, 0x35, 0x6b, 0x6e, 0xa4, 0x93, 0xe2, 0x01, 0xb2, 0x37, 0x3d, 0xd3, 0x82,
	0xb7, 0x90, 0x59, 0x27, 0x8e, 0xcf, 0x60, 0x84, 0x81, 0x5c, 0x92, 0x59, 0xf5, 0x62, 0x08, 0x11,
	0xd2, 0x4f, 0x3d, 0x90, 0x1f, 0xc8, 0xa4, 0xd7, 0xc8, 0xe1, 0xfa, 0x87, 0x8c, 0x51, 0x23, 0xf1,
	0x4b, 0x9f, 0x8b, 0xd6, 0xed, 0xfb, 0x53, 0xdf, 0x5f, 0x03, 0x4f, 0x6a, 0xd6, 0xe4, 0x32, 0x18,
	0x7c, 0x8c, 0x2d, 0x69, 0xcd, 0x9a, 0xa2, 0x2b, 0x03, 0xa6, 0x69, 0x3d, 0xc3, 0x51, 0xda, 0x8d,
	0x90, 0xbe, 0x6c, 0x76, 0xc2, 0x27, 0xc8, 0x5f, 0xc9, 0x06, 0xbc, 0x22, 0x4e, 0xf6, 0xb4, 0xdf,
	0x57, 0xd1, 0x44, 0x36, 0x71, 0x81, 0x1d, 0x94, 0xef, 0xae, 0x42, 0x59, 0x0a, 0x89, 0xd3, 0xdd,
	0xe7, 0x32, 0x1f, 0xe1, 0x3a, 0xcf, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0x5c, 0x96, 0x7a,
	0x32, 0x01, 0x00, 0x00,
}
