// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: message.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SendMessageService service

type SendMessageService interface {
	SendMessage(ctx context.Context, in *Message, opts ...client.CallOption) (*Reponse, error)
}

type sendMessageService struct {
	c    client.Client
	name string
}

func NewSendMessageService(name string, c client.Client) SendMessageService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "protos"
	}
	return &sendMessageService{
		c:    c,
		name: name,
	}
}

func (c *sendMessageService) SendMessage(ctx context.Context, in *Message, opts ...client.CallOption) (*Reponse, error) {
	req := c.c.NewRequest(c.name, "SendMessageService.SendMessage", in)
	out := new(Reponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SendMessageService service

type SendMessageServiceHandler interface {
	SendMessage(context.Context, *Message, *Reponse) error
}

func RegisterSendMessageServiceHandler(s server.Server, hdlr SendMessageServiceHandler, opts ...server.HandlerOption) error {
	type sendMessageService interface {
		SendMessage(ctx context.Context, in *Message, out *Reponse) error
	}
	type SendMessageService struct {
		sendMessageService
	}
	h := &sendMessageServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SendMessageService{h}, opts...))
}

type sendMessageServiceHandler struct {
	SendMessageServiceHandler
}

func (h *sendMessageServiceHandler) SendMessage(ctx context.Context, in *Message, out *Reponse) error {
	return h.SendMessageServiceHandler.SendMessage(ctx, in, out)
}
