// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Common               *Common  `protobuf:"bytes,2,opt,name=common,proto3" json:"common,omitempty"`
	Sentry               *Sentry  `protobuf:"bytes,3,opt,name=sentry,proto3" json:"sentry,omitempty"`
	Mail                 *Mail    `protobuf:"bytes,4,opt,name=mail,proto3" json:"mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetCommon() *Common {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Message) GetSentry() *Sentry {
	if m != nil {
		return m.Sentry
	}
	return nil
}

func (m *Message) GetMail() *Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

type Sentry struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	Level                string   `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Time                 string   `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Href                 string   `protobuf:"bytes,5,opt,name=href,proto3" json:"href,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sentry) Reset()         { *m = Sentry{} }
func (m *Sentry) String() string { return proto.CompactTextString(m) }
func (*Sentry) ProtoMessage()    {}
func (*Sentry) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Sentry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sentry.Unmarshal(m, b)
}
func (m *Sentry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sentry.Marshal(b, m, deterministic)
}
func (m *Sentry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sentry.Merge(m, src)
}
func (m *Sentry) XXX_Size() int {
	return xxx_messageInfo_Sentry.Size(m)
}
func (m *Sentry) XXX_DiscardUnknown() {
	xxx_messageInfo_Sentry.DiscardUnknown(m)
}

var xxx_messageInfo_Sentry proto.InternalMessageInfo

func (m *Sentry) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *Sentry) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *Sentry) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Sentry) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Sentry) GetHref() string {
	if m != nil {
		return m.Href
	}
	return ""
}

func (m *Sentry) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Common struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Common) Reset()         { *m = Common{} }
func (m *Common) String() string { return proto.CompactTextString(m) }
func (*Common) ProtoMessage()    {}
func (*Common) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Common) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common.Unmarshal(m, b)
}
func (m *Common) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common.Marshal(b, m, deterministic)
}
func (m *Common) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common.Merge(m, src)
}
func (m *Common) XXX_Size() int {
	return xxx_messageInfo_Common.Size(m)
}
func (m *Common) XXX_DiscardUnknown() {
	xxx_messageInfo_Common.DiscardUnknown(m)
}

var xxx_messageInfo_Common proto.InternalMessageInfo

func (m *Common) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Common) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Mail struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}
func (*Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail.Unmarshal(m, b)
}
func (m *Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail.Marshal(b, m, deterministic)
}
func (m *Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail.Merge(m, src)
}
func (m *Mail) XXX_Size() int {
	return xxx_messageInfo_Mail.Size(m)
}
func (m *Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Mail proto.InternalMessageInfo

func (m *Mail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Mail) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Mail) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Mail) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Mail) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Mail) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Reponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reponse) Reset()         { *m = Reponse{} }
func (m *Reponse) String() string { return proto.CompactTextString(m) }
func (*Reponse) ProtoMessage()    {}
func (*Reponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Reponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reponse.Unmarshal(m, b)
}
func (m *Reponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reponse.Marshal(b, m, deterministic)
}
func (m *Reponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reponse.Merge(m, src)
}
func (m *Reponse) XXX_Size() int {
	return xxx_messageInfo_Reponse.Size(m)
}
func (m *Reponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Reponse.DiscardUnknown(m)
}

var xxx_messageInfo_Reponse proto.InternalMessageInfo

func (m *Reponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Reponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterType((*Sentry)(nil), "protos.Sentry")
	proto.RegisterType((*Common)(nil), "protos.Common")
	proto.RegisterType((*Mail)(nil), "protos.Mail")
	proto.RegisterType((*Reponse)(nil), "protos.Reponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x4e, 0xc3, 0x30,
	0x0c, 0x55, 0xbb, 0xae, 0x63, 0x1e, 0x0c, 0x14, 0x71, 0xa8, 0x76, 0x9a, 0x7a, 0x40, 0x3b, 0x6d,
	0xd2, 0x90, 0xf8, 0x01, 0xc4, 0x71, 0x1c, 0xd2, 0x2f, 0x28, 0x9d, 0x37, 0x82, 0x9a, 0xa6, 0x4a,
	0xa2, 0xa1, 0xfd, 0x02, 0x17, 0x6e, 0x7c, 0x2f, 0x8a, 0x93, 0x96, 0x4d, 0x9a, 0x38, 0xd5, 0x7e,
	0x7e, 0xb6, 0xdf, 0x73, 0x03, 0x37, 0x12, 0x8d, 0x29, 0xf7, 0xb8, 0x6c, 0xb5, 0xb2, 0x8a, 0xa5,
	0xf4, 0x31, 0xf9, 0x77, 0x04, 0xa3, 0x8d, 0xaf, 0x30, 0x06, 0x89, 0x3d, 0xb6, 0x98, 0x45, 0xf3,
	0x68, 0x31, 0xe6, 0x14, 0xb3, 0x07, 0x48, 0x2b, 0x25, 0xa5, 0x6a, 0xb2, 0x78, 0x1e, 0x2d, 0x26,
	0xeb, 0xa9, 0xef, 0x37, 0xcb, 0x67, 0x42, 0x79, 0xa8, 0x3a, 0x9e, 0xc1, 0xc6, 0xea, 0x63, 0x36,
	0x38, 0xe7, 0x15, 0x84, 0xf2, 0x50, 0x65, 0x73, 0x48, 0x64, 0x29, 0xea, 0x2c, 0x21, 0xd6, 0x75,
	0xc7, 0xda, 0x94, 0xa2, 0xe6, 0x54, 0xc9, 0x7f, 0x22, 0x48, 0x8b, 0x8e, 0x3c, 0x69, 0xb5, 0xfa,
	0xc0, 0xca, 0xbe, 0x96, 0xb2, 0xd3, 0x75, 0x0a, 0xb1, 0x7b, 0x18, 0xd6, 0x78, 0xc0, 0x9a, 0xd4,
	0x8d, 0xb9, 0x4f, 0xc8, 0x88, 0x90, 0x48, 0x52, 0x9c, 0x11, 0x21, 0x91, 0x65, 0x30, 0x0a, 0x17,
	0xa0, 0xdd, 0x63, 0xde, 0xa5, 0x8e, 0xfd, 0xae, 0x71, 0x97, 0x0d, 0x3d, 0xdb, 0xc5, 0xfd, 0x29,
	0xd2, 0xbf, 0x53, 0xe4, 0x4f, 0x90, 0x7a, 0xd3, 0x17, 0x0f, 0x75, 0x32, 0x3f, 0x3e, 0x9b, 0x9f,
	0x7f, 0x45, 0x90, 0x38, 0x7f, 0x4e, 0xac, 0x15, 0xb6, 0xee, 0xfa, 0x7c, 0xe2, 0x86, 0xed, 0xb4,
	0x92, 0xa1, 0x8b, 0x62, 0x36, 0x85, 0xd8, 0xaa, 0x20, 0x3f, 0xb6, 0xea, 0x1f, 0xf1, 0x33, 0xb8,
	0x6a, 0x4b, 0x63, 0x3e, 0x95, 0xde, 0x06, 0x03, 0x7d, 0x7e, 0xd1, 0xc4, 0x0a, 0x46, 0x1c, 0x5b,
	0xd5, 0x18, 0x5a, 0x5c, 0xa9, 0xad, 0x57, 0x33, 0xe4, 0x14, 0xb3, 0x3b, 0x18, 0x48, 0xb3, 0x0f,
	0x5a, 0x5c, 0xb8, 0x7e, 0x01, 0x56, 0x60, 0xb3, 0x0d, 0x6f, 0xa4, 0x40, 0x7d, 0x10, 0x15, 0xb2,
	0x15, 0x4c, 0x4e, 0x50, 0x76, 0xdb, 0xff, 0x47, 0x0f, 0xcc, 0x7a, 0x20, 0x2c, 0x7b, 0xf3, 0xef,
	0xed, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xfc, 0x6a, 0xe7, 0x87, 0x02, 0x00, 0x00,
}
